# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ocr_pb2 as ocr__pb2


class OCRStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Character = channel.unary_unary(
                '/ocr.OCR/Character',
                request_serializer=ocr__pb2.CharacterBody.SerializeToString,
                response_deserializer=ocr__pb2.CharacterReply.FromString,
                )


class OCRServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Character(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OCRServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Character': grpc.unary_unary_rpc_method_handler(
                    servicer.Character,
                    request_deserializer=ocr__pb2.CharacterBody.FromString,
                    response_serializer=ocr__pb2.CharacterReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ocr.OCR', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OCR(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Character(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ocr.OCR/Character',
            ocr__pb2.CharacterBody.SerializeToString,
            ocr__pb2.CharacterReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
